  const TourDetail = [
  {
    id: 1,
    name: "Oeschinensee ",
    imageSrc: "https://hblimg.mmtcdn.com/content/hubble/img/leh/mmt/destination/m_leh-landscape_l_400_640.jpg",
    imageAlt: "Goa beach",
    price: "$299",
    color: "Beach",
    category: "Adventure", 
  },
    {
    id: 2,
    name: "serpentine road ",
    imageSrc: "https://hblimg.mmtcdn.com/content/hubble/img/Kathmandu_Resized/mmt/activities/m_Kathmandu_2-min_l_608_1000.jpg",
    imageAlt: "Goa beach",
    price: "$299",
    color: "Beach",
    category: "Adventure", 
  },
      {
    id: 3,
    name: " Manali",
    imageSrc: "https://hblimg.mmtcdn.com/content/hubble/img/manali/mmt/destination/m_Landscape_l_400_640.jpg",
    imageAlt: "Goa beach",
    price: "$299",
    color: "Beach",
    category: "Adventure", 
  },    {
    id: 4,
    name: " Ooty",
    imageSrc: "https://hblimg.mmtcdn.com/content/hubble/img/states_img/mmt/activities/m_Manipur_landscape_3_l_563_1000.jpg",
    imageAlt: "Goa beach",
    price: "$299",
    color: "Beach",
    category: "Adventure", 
  }, 
     {
    id: 5,
    name: "AUli",
    imageSrc: "https://hblimg.mmtcdn.com/content/hubble/img/aulidestimage/mmt/activities/m_Auli_MarNew_2_l_800_1200.png",
    imageAlt: "Goa beach",
    price: "$299",
    color: "Beach",
    category: "Adventure", 
  },    {
    id: 6,
    name: "Mahabaleshwar",
    imageSrc: "https://hblimg.mmtcdn.com/content/hubble/img/new_dest_imagemar/mmt/activities/m_mahabaleshwar_3_l_648_1194.jpg",
    imageAlt: "Goa beach",
    price: "$299",
    color: "Beach",
    category: "Adventure", 
  },
  {
    id: 7,
    name: "Munnar",
    imageSrc: "https://hblimg.mmtcdn.com/content/hubble/img/munnar/mmt/destination/m_destination-munnar-landscape_l_400_640.jpg",
    imageAlt: "Goa beach",
    price: "$299",
    color: "Beach",
    category: "Adventure", 
  },
 

  {
    id: 8,
    name: "Karjat",
    imageSrc: "https://hblimg.mmtcdn.com/content/hubble/img/desttvimg/mmt/destination/m_Karjat_tv_destination_img_2_l_563_881.jpg",
    price: "$299",
    color: "Beach",
    category: "Adventure", 
  },
 
{
    id: 9,
    name: "Naggar Village",
    imageSrc: "https://img.invinciblengo.org/iconscout/f:jpeg/w:800/h:0/rt:fit/plain/https://invincible.s3.wasabisys.com/attraction/53e7d28e-6e07-471c-a503-a251d6444194",
    imageAlt: "Goa beach",
    price: "$299",
    color: "Beach",
    category: "Treckking", 
  },
    {
    id: 10,
    name: " Khari Nadi",
    imageSrc: "https://static.wixstatic.com/media/2eb27c_a2c088165a21438da51333120546d605~mv2.jpg/v1/fill/w_1175,h_660,al_c,q_85,usm_0.66_1.00_0.01,enc_avif,quality_auto/2eb27c_a2c088165a21438da51333120546d605~mv2.jpg",
    price: "$299",
    color: "Beach",
    category: "Treckking", 
  },
      {
    id: 11,
    name: "Majestic Mountain",
    imageSrc: "https://static.wixstatic.com/media/2eb27c_4f50cca22c45422cb796793fa5f08e5d~mv2.jpg/v1/fill/w_1175,h_784,al_c,q_85,usm_0.66_1.00_0.01,enc_avif,quality_auto/2eb27c_4f50cca22c45422cb796793fa5f08e5d~mv2.jpg",
    imageAlt: "Goa beach",
    price: "$299",
    color: "Beach",
    category: "Treckking", 
  },    {
    id: 12,
    name: " Phugtal Monastery",
    imageSrc: "https://img.invinciblengo.org/iconscout/f:jpeg/w:600/h:0/rt:fit/plain/https://invincible.s3.wasabisys.com/schedule/e88a0c55-4155-490b-936a-cb370b3ccb0a",
    imageAlt: "Goa beach",
    price: "$299",
    color: "Beach",
    category: "Treckking", 
  }, 
     {
    id: 13,
    name: " Munnar",
    imageSrc: "https://img.invinciblengo.org/iconscout/f:jpeg/w:600/h:0/rt:fit/plain/https://invincible.s3.wasabisys.com/schedule/e88a0c55-4155-490b-936a-cb370b3ccb0a",
    imageAlt: "Goa beach",
    price: "$299",
    color: "Beach",
    category: "Treckking", 
  },    {
    id: 14,
    name: "Majestic Goa Getaway",
    imageSrc: "https://adventure-holidays-slovenia.b-cdn.net/wp-content/uploads/People-kayaking-on-Soca-scaled.webp",
    imageAlt: "Goa beach",
    price: "$299",
    color: "Beach",
    category: "Treckking", 
  },
  {
    id: 15,
    name: "Majestic Goa Getaway",
    imageSrc: "https://sp-ao.shortpixel.ai/client/to_webp,q_glossy,ret_img,w_742,h_1024/https://blog.unimonitravel.com/wp-content/uploads/2024/10/ADV-MID-742x1024.webp",
    imageAlt: "Goa beach",
    price: "$299",
    color: "Beach",
    category: "Treckking", 
  },
 

  {
    id: 16,
    name: "Majestic Goa Getaway",
    imageSrc: "https://media.istockphoto.com/id/1511069617/photo/women-hikers-embracing-the-untamed-beauty-of-tasmania-through-exhilarating-bushwalking.jpg?s=612x612&w=0&k=20&c=T8sDlMsvby3usWMjkdvQobeMycD0YkwyreeRF9VFWE8=",
    price: "$299",
    color: "Beach",
    category: "Beaches", 
  },
   {
    id: 17,
    name: "Oeschinensee (Oeschinen lake)",
    imageSrc: "https://media.istockphoto.com/id/517599616/photo/panorama-view-of-oeschinensee-on-bernese-oberla.jpg?s=612x612&w=0&k=20&c=PkX0ebgjcsBK4_dnDGClLGspqI4bUZqGB-qUyBnoyIo=",
    imageAlt: "Goa beach",
    price: "$299",
    color: "Beach",
    category: "Beaches", 
  },
    {
    id: 18,
    name: "serpentine road (Majola Pass)",
    imageSrc: "https://media.istockphoto.com/id/1822247032/photo/aerial-view-of-serpentine-road-in-swiss-alps-in-autumn.jpg?s=612x612&w=0&k=20&c=NCL-I5tlWaQ1HDnTGxIHgtvxDvbXlEgS_YUfC0-TxFc=",
    imageAlt: "Goa beach",
    price: "$299",
    color: "Beach",
    category: "Beaches", 
  },
      {
    id: 19,
    name: " Matterhorn mountain",
    imageSrc: "https://media.istockphoto.com/id/2207926103/photo/young-skier-skiing-downhill-at-zermatt-ski-resort-switzerland.jpg?s=612x612&w=0&k=20&c=Y8YYjczwxbQe5B5J8J-ZdHhNBjA7U7uQejBWqBC08XY=",
    imageAlt: "Goa beach",
    price: "$299",
    color: "Beach",
    category: "Beaches", 
  },    {
    id: 20,
    name: " viaduct",
    imageSrc: "https://media.istockphoto.com/id/898687414/photo/scenic-view-of-train-on-viaduct-in-switzerland.jpg?s=612x612&w=0&k=20&c=8tYidlTxy7_bYsRhE6ZF6-iRpQ57k9u2LZmTduVYh_8=",
    imageAlt: "Goa beach",
    price: "$299",
    color: "Beach",
    category: "Beaches", 
  }, 
     {
    id: 21,
    name: "Majestic Goa Getaway",
    imageSrc: "https://images.unsplash.com/photo-1528543606781-2f6e6857f318?fm=jpg&q=60&w=3000&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YWR2ZW50dXJlJTIwdHJhdmVsfGVufDB8fDB8fHww",
    imageAlt: "Goa beach",
    price: "$299",
    color: "Beach",
    category: "Beaches", 
  },    {
    id: 22,
    name: "Majestic Goa Getaway",
    imageSrc: "https://adventure-holidays-slovenia.b-cdn.net/wp-content/uploads/People-kayaking-on-Soca-scaled.webp",
    imageAlt: "Goa beach",
    price: "$299",
    color: "Beach",
    category: "Beaches", 
  },
  {
    id: 23,
    name: "Majestic Goa Getaway",
    imageSrc: "https://sp-ao.shortpixel.ai/client/to_webp,q_glossy,ret_img,w_742,h_1024/https://blog.unimonitravel.com/wp-content/uploads/2024/10/ADV-MID-742x1024.webp",
    imageAlt: "Goa beach",
    price: "$299",
    color: "Beach",
    category: "Beaches", 
  },
 

  {
    id: 24,
    name: "Majestic Goa Getaway",
    imageSrc: "https://media.istockphoto.com/id/1511069617/photo/women-hikers-embracing-the-untamed-beauty-of-tasmania-through-exhilarating-bushwalking.jpg?s=612x612&w=0&k=20&c=T8sDlMsvby3usWMjkdvQobeMycD0YkwyreeRF9VFWE8=",
    price: "$299",
    color: "Beach",
    category: "Beaches", 
  },
    {
    id: 25,
    name: "Oeschinensee (Oeschinen lake)",
    imageSrc: "https://media.istockphoto.com/id/517599616/photo/panorama-view-of-oeschinensee-on-bernese-oberla.jpg?s=612x612&w=0&k=20&c=PkX0ebgjcsBK4_dnDGClLGspqI4bUZqGB-qUyBnoyIo=",
    imageAlt: "Goa beach",
    price: "$299",
    color: "Beach",
    category: "Heritages", 
  },
    {
    id: 26,
    name: "serpentine road (Majola Pass)",
    imageSrc: "https://media.istockphoto.com/id/1822247032/photo/aerial-view-of-serpentine-road-in-swiss-alps-in-autumn.jpg?s=612x612&w=0&k=20&c=NCL-I5tlWaQ1HDnTGxIHgtvxDvbXlEgS_YUfC0-TxFc=",
    imageAlt: "Goa beach",
    price: "$299",
    color: "Beach",
    category: "Heritages", 
  },
      {
    id: 27,
    name: " Matterhorn mountain",
    imageSrc: "https://media.istockphoto.com/id/2207926103/photo/young-skier-skiing-downhill-at-zermatt-ski-resort-switzerland.jpg?s=612x612&w=0&k=20&c=Y8YYjczwxbQe5B5J8J-ZdHhNBjA7U7uQejBWqBC08XY=",
    imageAlt: "Goa beach",
    price: "$299",
    color: "Beach",
    category: "Heritages", 
  },    {
    id: 28,
    name: " viaduct",
    imageSrc: "https://media.istockphoto.com/id/898687414/photo/scenic-view-of-train-on-viaduct-in-switzerland.jpg?s=612x612&w=0&k=20&c=8tYidlTxy7_bYsRhE6ZF6-iRpQ57k9u2LZmTduVYh_8=",
    imageAlt: "Goa beach",
    price: "$299",
    color: "Beach",
    category: "Heritages", 
  }, 
     {
    id: 29,
    name: "Majestic Goa Getaway",
    imageSrc: "https://images.unsplash.com/photo-1528543606781-2f6e6857f318?fm=jpg&q=60&w=3000&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YWR2ZW50dXJlJTIwdHJhdmVsfGVufDB8fDB8fHww",
    imageAlt: "Goa beach",
    price: "$299",
    color: "Beach",
    category: "Heritages", 
  },    {
    id: 30,
    name: "Majestic Goa Getaway",
    imageSrc: "https://adventure-holidays-slovenia.b-cdn.net/wp-content/uploads/People-kayaking-on-Soca-scaled.webp",
    imageAlt: "Goa beach",
    price: "$299",
    color: "Beach",
    category: "Heritages", 
  },
  {
    id: 31,
    name: "Majestic Goa Getaway",
    imageSrc: "https://sp-ao.shortpixel.ai/client/to_webp,q_glossy,ret_img,w_742,h_1024/https://blog.unimonitravel.com/wp-content/uploads/2024/10/ADV-MID-742x1024.webp",
    imageAlt: "Goa beach",
    price: "$299",
    color: "Beach",
    category: "Heritages", 
  },
 

  {
    id: 32,
    name: "Majestic Goa Getaway",
    imageSrc: "https://media.istockphoto.com/id/1511069617/photo/women-hikers-embracing-the-untamed-beauty-of-tasmania-through-exhilarating-bushwalking.jpg?s=612x612&w=0&k=20&c=T8sDlMsvby3usWMjkdvQobeMycD0YkwyreeRF9VFWE8=",
    price: "$299",
    color: "Beach",
    category: "Heritages", 
  },
 


];
export default TourDetail;