  const TourDetail = [
  {
    id: 1,
    name: "Oeschinensee ",
    imageSrc: "https://hblimg.mmtcdn.com/content/hubble/img/leh/mmt/destination/m_leh-landscape_l_400_640.jpg",
    imageAlt: "Goa beach",
    price: "$299",
    color: "Beach",
    category: "Adventure", 
  },
    {
    id: 2,
    name: "serpentine road ",
    imageSrc: "https://hblimg.mmtcdn.com/content/hubble/img/Kathmandu_Resized/mmt/activities/m_Kathmandu_2-min_l_608_1000.jpg",
    imageAlt: "Goa beach",
    price: "$299",
    color: "Beach",
    category: "Adventure", 
  },
      {
    id: 3,
    name: " Manali",
    imageSrc: "https://hblimg.mmtcdn.com/content/hubble/img/manali/mmt/destination/m_Landscape_l_400_640.jpg",
    imageAlt: "Goa beach",
    price: "$299",
    color: "Beach",
    category: "Adventure", 
  },    {
    id: 4,
    name: " Ooty",
    imageSrc: "https://hblimg.mmtcdn.com/content/hubble/img/states_img/mmt/activities/m_Manipur_landscape_3_l_563_1000.jpg",
    imageAlt: "Goa beach",
    price: "$299",
    color: "Beach",
    category: "Adventure", 
  }, 
     {
    id: 5,
    name: "Auli",
    imageSrc: "https://hblimg.mmtcdn.com/content/hubble/img/aulidestimage/mmt/activities/m_Auli_MarNew_2_l_800_1200.png",
    imageAlt: "Goa beach",
    price: "$299",
    color: "Beach",
    category: "Adventure", 
  },  
    {
    id: 6,
    name: "Mahabaleshwar",
    imageSrc: "https://hblimg.mmtcdn.com/content/hubble/img/new_dest_imagemar/mmt/activities/m_mahabaleshwar_3_l_648_1194.jpg",
    imageAlt: "Goa beach",
    price: "$299",
    color: "Beach",
    category: "Adventure", 
  },
  {
    id: 7,
    name: "Munnar",
    imageSrc: "https://hblimg.mmtcdn.com/content/hubble/img/munnar/mmt/destination/m_destination-munnar-landscape_l_400_640.jpg",
    imageAlt: "Goa beach",
    price: "$299",
    color: "Beach",
    category: "Adventure", 
  },
 

  {
    id: 8,
    name: "Karjat",
    imageSrc: "https://hblimg.mmtcdn.com/content/hubble/img/desttvimg/mmt/destination/m_Karjat_tv_destination_img_2_l_563_881.jpg",
    price: "$299",
    color: "Beach",
    category: "Adventure", 
  },
 
{
    id: 9,
    name: "Naggar Village",
    imageSrc: "https://img.invinciblengo.org/iconscout/f:jpeg/w:800/h:0/rt:fit/plain/https://invincible.s3.wasabisys.com/attraction/53e7d28e-6e07-471c-a503-a251d6444194",
    imageAlt: "Goa beach",
    price: "₹7299",
    color: "Beach",
    category: "Treckking", 
  },
    {
    id: 10,
    name: " Khari Nadi",
    imageSrc: "https://static.wixstatic.com/media/2eb27c_a2c088165a21438da51333120546d605~mv2.jpg/v1/fill/w_1175,h_660,al_c,q_85,usm_0.66_1.00_0.01,enc_avif,quality_auto/2eb27c_a2c088165a21438da51333120546d605~mv2.jpg",
    price: "₹2499",
    color: "Beach",
    category: "Treckking", 
  },
      {
    id: 11,
    name: "Macau",
    imageSrc: "https://hblimg.mmtcdn.com/content/hubble/img/macau/mmt/destination/m_Macau_activity_heritage_l_691_1040.jpg",
    imageAlt: "Goa beach",
    price: "₹2399",
    color: "Beach",
    category: "Treckking", 
  },    {
    id: 12,
    name: "Manali",
    imageSrc: "https://hblimg.mmtcdn.com/content/hubble/img/destimg/mmt/destination/t_ufs/m_Manali_main_tv_destination_img_1_l_1021_1529.jpg",
    imageAlt: "Goa beach",
    price: "₹4299",
    color: "Beach",
    category: "Treckking", 
  }, 
     {
    id: 13,
    name: " Munnar",
    imageSrc: "https://img.invinciblengo.org/iconscout/f:jpeg/w:600/h:0/rt:fit/plain/https://invincible.s3.wasabisys.com/schedule/e88a0c55-4155-490b-936a-cb370b3ccb0a",
    imageAlt: "Goa beach",
    price: "₹4565",
    color: "Beach",
    category: "Treckking", 
  },    {
    id: 14,
    name: "Majestic Goa Getaway",
    imageSrc: "https://adventure-holidays-slovenia.b-cdn.net/wp-content/uploads/People-kayaking-on-Soca-scaled.webp",
    imageAlt: "Goa beach",
    price: "₹6557",
    color: "Beach",
    category: "Treckking", 
  },
  {
    id: 15,
    name: "Dehradun",
    imageSrc: "https://hblimg.mmtcdn.com/content/hubble/img/desttvimg/mmt/destination/t_ufs/m_Dehradun_tv_destination_img_4_l_738_1108.jpg",
    imageAlt: "Goa beach",
    price: "₹7886",
    color: "Beach",
    category: "Treckking", 
  },
    {
    id: 95,
    name: "Majestic Goa Getaway",
    imageSrc: "https://hblimg.mmtcdn.com/content/hubble/img/states_img/mmt/activities/m_Manipur_landscape_3_l_563_1000.jpg",
    imageAlt: "Goa beach",
    price: "₹7886",
    color: "Beach",
    category: "Treckking", 
  },
 

  {
    id: 16,
    name: "Goa ",
    imageSrc: "https://hblimg.mmtcdn.com/content/hubble/img/destimg/mmt/destination/t_trp/m_goa_main_tv_destination_img_1_l_759_1138.jpg?im=Resize=(480,480)",
    price: "$299",
    color: "Beach",
    category: "Beaches", 
  },
   {
    id: 17,
    name: "Pondicherry",
    imageSrc: "https://hblimg.mmtcdn.com/content/hubble/img/pondicherry/mmt/destination/m_Pondicherry_activity_beach_l_382_691.jpg",
    imageAlt: "Goa beach",
    price: "₹4589",
    color: "Beach",
    category: "Beaches", 
  },
    {
    id: 18,
    name: "Promenade",
    imageSrc: "https://hblimg.mmtcdn.com/content/hubble/img/pondicherry/mmt/activities/t_ufs/m_activities-pondicherry-promenade-beach_l_400_640.jpg",
    imageAlt: "Goa beach",
    price: "$299",
    color: "Beach",
    category: "Beaches", 
  },
      {
    id: 19,
    name: "  phuket",
    imageSrc: "https://hblimg.mmtcdn.com/content/hubble/img/desttvimg/mmt/destination/t_ufs/m_Phuket_tv_destination_img_1_l_629_1005.jpg",
    imageAlt: "Goa beach",
    price: "$299",
    color: "Beach",
    category: "Beaches", 
  },    {
    id: 20,
    name: " pattay",
    imageSrc: "https://hblimg.mmtcdn.com/content/hubble/img/desttvimg/mmt/destination/t_ufs/m_pattaya_tv_destination_img_1_l_803_1206.jpg",
    imageAlt: "Goa beach",
    price: "$299",
    color: "Beach",
    category: "Beaches", 
  }, 
     {
    id: 21,
    name: "Havelock",
    imageSrc: "https://hblimg.mmtcdn.com/content/hubble/img/destimg/mmt/destination/t_ufs/m_havelock_tv_destination_img_1_l_813_1446.jpg",
    imageAlt: "Goa beach",
    price: "$299",
    color: "Beach",
    category: "Beaches", 
  },    {
    id: 22,
    name: "Digha",
    imageSrc: "https://hblimg.mmtcdn.com/content/hubble/img/desttvimg/mmt/destination/t_ufs/m_Digha_tv_destination_img_1_l_821_1321.jpg",
    imageAlt: "Goa beach",
    price: "$299",
    color: "Beach",
    category: "Beaches", 
  },
  {
    id: 23,
    name: "Bali",
    imageSrc: "https://hblimg.mmtcdn.com/content/hubble/img/desttvimg/mmt/destination/t_ufs/m_Bali_tv_destination_img_1_l_771_1158.jpg",
    imageAlt: "Goa beach",
    price: "$299",
    color: "Beach",
    category: "Beaches", 
  },
 

    {
    id: 25,
    name: "Taj Mahal",
    imageSrc: "https://hblimg.mmtcdn.com/content/hubble/img/agra/mmt/activities/m_activities-agra-taj-mahal_l_400_640.jpg",
    imageAlt: "Goa beach",
    price: "$299",
    color: "Beach",
    category: "Heritages", 
  },
    {
    id: 26,
    name: "Red Fort",
    imageSrc: "https://hblimg.mmtcdn.com/content/hubble/img/delhi/mmt/activities/m_activities_delhi_red_fort_l_341_817.jpg",
    imageAlt: "Goa beach",
    price: "$299",
    color: "Beach",
    category: "Heritages", 
  },
      {
    id: 27,
    name: "Golden Temple",
    imageSrc: "https://hblimg.mmtcdn.com/content/hubble/img/amritsar/mmt/activities/m_activities_amritsar_golden_temple_l_427_639.jpg",
    imageAlt: "Goa beach",
    price: "$299",
    color: "Beach",
    category: "Heritages", 
  },    {
    id: 28,
    name: " Humayun's Tomb",
    imageSrc: "https://hblimg.mmtcdn.com/content/hubble/img/delhi/mmt/activities/m_activities_delhi_humayun_s_tomb_l_435_653.jpg",
    imageAlt: "Goa beach",
    price: "$299",
    color: "Beach",
    category: "Heritages", 
  }, 
     {
    id: 29,
    name: "India Gate",
    imageSrc: "https://hblimg.mmtcdn.com/content/hubble/img/delhi/mmt/activities/m_activities_delhi_india_gate_1_l_442_663.jpg",
    imageAlt: "Goa beach",
    price: "$299",
    color: "Beach",
    category: "Heritages", 
  },    {
    id: 30,
    name: "Augada Fort",
    imageSrc: "https://hblimg.mmtcdn.com/content/hubble/img/goa/mmt/activities/m_Fort%20Aguada_6_l_436_654.jpg",
    imageAlt: "Goa beach",
    price: "$299",
    color: "Beach",
    category: "Heritages", 
  },
  {
    id: 31,
    name: "State of Unity",
    imageSrc: "https://hblimg.mmtcdn.com/content/hubble/img/vadodara/mmt/activities/m_activities_vadodara_statue_of_unity_l_405_810.jpg",
    imageAlt: "Goa beach",
    price: "$299",
    color: "Beach",
    category: "Heritages", 
  },
 

  {
    id: 32,
    name: "Mysore palace",
    imageSrc: "https://hblimg.mmtcdn.com/content/hubble/img/mysore/mmt/activities/m_activities_Mysore_Mysore%20Palace_l_386_579.jpg",
    color: "Beach",
    category: "Heritages", 
  },
 


];
export default TourDetail;